### ISSUE TITLE
Configuration Display Icon On Left for LSPs

### ISSUE THREAD

**Issue by mmanning2-chwy** [j-hui/fidget.nvim#169]
Hello, I am having difficulty configuring this.
I've read through the documentation and issues and despite my best efforts having difficulty figuring out we're actually supposed to configure the default notifications for LSPs.

Here is my setup:
```lua
require 'fidget'.setup {
  notification = {
    override_vim_notify = true,
    configs = {
      default = vim.tbl_extend(require('fidget.notification').default_config, {
        icon_on_left = true,
      }),
    },
  }
}
```
And I see this as a result:
![Screenshot 2023-11-17 at 4 46 42 PM](https://github.com/j-hui/fidget.nvim/assets/109112307/1ea16b52-919a-4dbb-a74c-a3067296259f)

Do the LSPs have to be individually overridden with notification configs or do they have their separate configurations?
Do I have to include the default configs if I am overriding only a small section?
Is icon_on_left broken?

Thank you

**Comment by j-hui** [comment]
Sorry the configuration is so complicated, and thank you for the patience to dig through my code! I'll try to make the options more user-friendly over time.

In the meantime, I've pushed https://github.com/j-hui/fidget.nvim/commit/bd0b8b644d4fb293dc4df2718b1f2df3abd90767, which makes LSP notification configs inherit from whatever is set as the default. So your config should work now (provided you change add a valid `{behavior}` argument to `vim.tbl_extend()`, i.e., `"force"`). I had totally overlooked how the progress subsystem's generated configs would ignore users' defaults.

**Comment by mmanning2-chwy** [comment]
Thank you for your quick reply and work.
After adding the behavior argument (woops) and pulling changes I am still not seeing icons appear on the left.
Even with a simplified configuration, the icons still appear on the right.

**Comment by j-hui** [comment]
Can you please share your latest config, and also verify that the cloned fidget plugin repo has the commit bd0b8b6?

**Comment by mmanning2-chwy** [comment]
I went to confirm via packer that the correct version was installed. It was, navigated to the `notification.lua` file in question and saw the change present locally. Restarted vim and it magically started working.

I can only assume something got cached? Very strange. I assume this is a me a problem.

It's working now. Thank you :)

**Comment by j-hui** [comment]
> Restarted vim and it magically started working with the icons placed on the left side.
>
> I can only assume something got cached? Very strange. I assume this is a me a problem.

That's really bizarre, but I'm glad you got it to work eventually!
